// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package token

import (
	"context"

	"go-zero-fast/service/sys/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IDRequest         = pb.IDRequest
	IDsRequest        = pb.IDsRequest
	MenuInfo          = pb.MenuInfo
	MenuInfoList      = pb.MenuInfoList
	Meta              = pb.Meta
	Model             = pb.Model
	NoDataResponse    = pb.NoDataResponse
	PageInfo          = pb.PageInfo
	RoleInfo          = pb.RoleInfo
	RoleListRequest   = pb.RoleListRequest
	RoleListResponse  = pb.RoleListResponse
	RoleUpdateRequest = pb.RoleUpdateRequest
	TokenInfo         = pb.TokenInfo
	TokenInfoRequest  = pb.TokenInfoRequest
	TokenInfoResponse = pb.TokenInfoResponse
	UserInfo          = pb.UserInfo
	UserInfoResponse  = pb.UserInfoResponse
	UsernameRequest   = pb.UsernameRequest
	UsernameResponse  = pb.UsernameResponse

	Token interface {
		// 生成Token
		CreateToken(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	}

	defaultToken struct {
		cli zrpc.Client
	}
)

func NewToken(cli zrpc.Client) Token {
	return &defaultToken{
		cli: cli,
	}
}

// 生成Token
func (m *defaultToken) CreateToken(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	client := pb.NewTokenClient(m.cli.Conn())
	return client.CreateToken(ctx, in, opts...)
}
