// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package server

import (
	"context"

	"go-zero-fast/service/sys/rpc/internal/logic/menu"
	"go-zero-fast/service/sys/rpc/internal/svc"
	"go-zero-fast/service/sys/rpc/pb"
)

type MenuServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMenuServer
}

func NewMenuServer(svcCtx *svc.ServiceContext) *MenuServer {
	return &MenuServer{
		svcCtx: svcCtx,
	}
}

// 根据角色id 获取菜单 -- 目前系统用这个 可以方便用户切换角色获取不一样的菜单
func (s *MenuServer) GetMenuListByRoleId(ctx context.Context, in *pb.IDRequest) (*pb.MenuInfoList, error) {
	l := menulogic.NewGetMenuListByRoleIdLogic(ctx, s.svcCtx)
	return l.GetMenuListByRoleId(in)
}

// 获取菜单列表
func (s *MenuServer) GetMenuList(ctx context.Context, in *pb.PageInfo) (*pb.MenuInfoList, error) {
	l := menulogic.NewGetMenuListLogic(ctx, s.svcCtx)
	return l.GetMenuList(in)
}
