// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package server

import (
	"context"

	"go-zero-fast/service/sys/rpc/internal/logic/user"
	"go-zero-fast/service/sys/rpc/internal/svc"
	"go-zero-fast/service/sys/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 根据用户名获取用户详情
func (s *UserServer) GetUserByUsername(ctx context.Context, in *pb.UsernameReq) (*pb.UsernameRes, error) {
	l := userlogic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}
