// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package server

import (
	"context"

	"go-zero-fast/service/sys/rpc/internal/logic/token"
	"go-zero-fast/service/sys/rpc/internal/svc"
	"go-zero-fast/service/sys/rpc/pb"
)

type TokenServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTokenServer
}

func NewTokenServer(svcCtx *svc.ServiceContext) *TokenServer {
	return &TokenServer{
		svcCtx: svcCtx,
	}
}

// 生成Token
func (s *TokenServer) CreateToken(ctx context.Context, in *pb.TokenInfoRequest) (*pb.TokenInfoResponse, error) {
	l := tokenlogic.NewCreateTokenLogic(ctx, s.svcCtx)
	return l.CreateToken(in)
}
