// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package role

import (
	"context"

	"go-zero-fast/service/sys/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IDReq        = pb.IDReq
	IDSReq       = pb.IDSReq
	MenuInfo     = pb.MenuInfo
	MenuInfoList = pb.MenuInfoList
	Meta         = pb.Meta
	Model        = pb.Model
	PageInfo     = pb.PageInfo
	RoleInfo     = pb.RoleInfo
	RoleListReq  = pb.RoleListReq
	RoleListRes  = pb.RoleListRes
	TokenInfo    = pb.TokenInfo
	TokenInfoReq = pb.TokenInfoReq
	TokenInfoRes = pb.TokenInfoRes
	UserInfo     = pb.UserInfo
	UserInfoRes  = pb.UserInfoRes
	UsernameReq  = pb.UsernameReq
	UsernameRes  = pb.UsernameRes

	Role interface {
		// 获取角色列表
		GetRoleList(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListRes, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

// 获取角色列表
func (m *defaultRole) GetRoleList(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListRes, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}
