// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	user "go-zero-fast/service/sys/api/internal/handler/user"
	usernoauth "go-zero-fast/service/sys/api/internal/handler/usernoauth"
	"go-zero-fast/service/sys/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 根据token获取用户信息
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取验证码
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: usernoauth.GetCaptchaHandler(serverCtx),
			},
			{
				// 系统用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: usernoauth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/sys"),
	)
}
