// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CaptchaInfo struct {
	CaptchaId string `json:"captchaId"`
	ImgPath   string `json:"imgPath"`
}

type CaptchaRes struct {
	CaptchaInfo
}

type LoginInfo struct {
	UserId uint64 `json:"userId"` // 用户id
	Token  string `json:"token"`  // 和前端交互的token
	Expire uint64 `json:"expire"` // 过期时间戳
}

type LoginReq struct {
	Username  string `json:"username" validate:"required,max=15"`       // 登录名称
	Password  string `json:"password" validate:"required,max=30,min=6"` // 密码
	CaptchaId string `json:"captchaId"  validate:"required,len=20"`     // 验证码id
	Captcha   string `json:"captcha" validate:"required,len=5"`         //验证码
}

type LoginRes struct {
	LoginInfo
}
