DROP TABLE IF EXISTS `sys_positions`;
CREATE TABLE `sys_positions` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `status` TINYINT UNSIGNED NULL DEFAULT 1 COMMENT '状态:1正常/2禁用',
    `sort` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '排序编号',
    `name` VARCHAR(255) NOT NULL COMMENT '职位名称',
    `code` INT UNSIGNED NOT NULL COMMENT '职位编码',
    `remark` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
    `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '软删除时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `position_code`(`code`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '职位信息表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;