// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package user

import (
	"context"

	"go-zero-fast/service/sys/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TokenInfo    = pb.TokenInfo
	TokenInfoReq = pb.TokenInfoReq
	TokenInfoRes = pb.TokenInfoRes
	UserInfo     = pb.UserInfo
	UsernameReq  = pb.UsernameReq
	UsernameRes  = pb.UsernameRes

	User interface {
		// 根据用户名获取用户详情
		GetUserByUsername(ctx context.Context, in *UsernameReq, opts ...grpc.CallOption) (*UsernameRes, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 根据用户名获取用户详情
func (m *defaultUser) GetUserByUsername(ctx context.Context, in *UsernameReq, opts ...grpc.CallOption) (*UsernameRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, in, opts...)
}
