// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package user

import (
	"context"

	"go-zero-fast/service/sys/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IDRequest         = pb.IDRequest
	IDsRequest        = pb.IDsRequest
	MenuInfo          = pb.MenuInfo
	MenuInfoList      = pb.MenuInfoList
	Meta              = pb.Meta
	Model             = pb.Model
	NoDataResponse    = pb.NoDataResponse
	PageInfo          = pb.PageInfo
	RoleInfo          = pb.RoleInfo
	RoleListRequest   = pb.RoleListRequest
	RoleListResponse  = pb.RoleListResponse
	RoleUpdateRequest = pb.RoleUpdateRequest
	TokenInfo         = pb.TokenInfo
	TokenInfoRequest  = pb.TokenInfoRequest
	TokenInfoResponse = pb.TokenInfoResponse
	UserInfo          = pb.UserInfo
	UserInfoResponse  = pb.UserInfoResponse
	UsernameRequest   = pb.UsernameRequest
	UsernameResponse  = pb.UsernameResponse

	User interface {
		// 根据用户名获取用户详情
		GetUserByUsername(ctx context.Context, in *UsernameRequest, opts ...grpc.CallOption) (*UsernameResponse, error)
		// 获取用户详细信息
		GetUserInfoById(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 根据用户名获取用户详情
func (m *defaultUser) GetUserByUsername(ctx context.Context, in *UsernameRequest, opts ...grpc.CallOption) (*UsernameResponse, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, in, opts...)
}

// 获取用户详细信息
func (m *defaultUser) GetUserInfoById(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUserInfoById(ctx, in, opts...)
}
