// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package server

import (
	"context"

	"go-zero-fast/service/sys/rpc/internal/logic/role"
	"go-zero-fast/service/sys/rpc/internal/svc"
	"go-zero-fast/service/sys/rpc/pb"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

// 获取角色列表
func (s *RoleServer) GetRoleList(ctx context.Context, in *pb.RoleListReq) (*pb.RoleListRes, error) {
	l := rolelogic.NewGetRoleListLogic(ctx, s.svcCtx)
	return l.GetRoleList(in)
}
