// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: sys.proto

package menu

import (
	"context"

	"go-zero-fast/service/sys/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IDRequest         = pb.IDRequest
	IDsRequest        = pb.IDsRequest
	MenuInfo          = pb.MenuInfo
	MenuInfoList      = pb.MenuInfoList
	Meta              = pb.Meta
	Model             = pb.Model
	NoDataResponse    = pb.NoDataResponse
	PageInfo          = pb.PageInfo
	RoleInfo          = pb.RoleInfo
	RoleListRequest   = pb.RoleListRequest
	RoleListResponse  = pb.RoleListResponse
	RoleUpdateRequest = pb.RoleUpdateRequest
	TokenInfo         = pb.TokenInfo
	TokenInfoRequest  = pb.TokenInfoRequest
	TokenInfoResponse = pb.TokenInfoResponse
	UserInfo          = pb.UserInfo
	UserInfoResponse  = pb.UserInfoResponse
	UsernameRequest   = pb.UsernameRequest
	UsernameResponse  = pb.UsernameResponse

	Menu interface {
		// 根据角色id 获取菜单 -- 目前系统用这个 可以方便用户切换角色获取不一样的菜单
		GetMenuListByRoleId(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*MenuInfoList, error)
		// 获取菜单列表
		GetMenuList(ctx context.Context, in *PageInfo, opts ...grpc.CallOption) (*MenuInfoList, error)
	}

	defaultMenu struct {
		cli zrpc.Client
	}
)

func NewMenu(cli zrpc.Client) Menu {
	return &defaultMenu{
		cli: cli,
	}
}

// 根据角色id 获取菜单 -- 目前系统用这个 可以方便用户切换角色获取不一样的菜单
func (m *defaultMenu) GetMenuListByRoleId(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*MenuInfoList, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.GetMenuListByRoleId(ctx, in, opts...)
}

// 获取菜单列表
func (m *defaultMenu) GetMenuList(ctx context.Context, in *PageInfo, opts ...grpc.CallOption) (*MenuInfoList, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.GetMenuList(ctx, in, opts...)
}
